inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls
from .views import home_view


urlpatterns = (([
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('items/', include('items.urls')),
    path("polls/", include("polls.urls")),
]) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   + debug_toolbar_urls())

items/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('item/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('create/', views.ItemCreateView.as_view(), name='create'),
]

polls/urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

items/models.py
from django.db import models


class TimestampMixin(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Inventory(TimestampMixin):
    name = models.CharField(max_length=64, default='')


class Tag(TimestampMixin):
    text = models.CharField(max_length=32, unique=True)


class Item(TimestampMixin):
    name = models.CharField(max_length=64, unique=True)
    weight = models.PositiveSmallIntegerField(default=100)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f'{self.name} ({self.weight})'


class Sword(Item):

    class Meta:
        proxy = True

    def make_damage(self):
        print('damage!')


class UserItem(Item):
    user_name = models.CharField(max_length=32)

makemigrations/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

inventory/views.py
from django.shortcuts import render
from django.core.cache import cache


def home_view(request):
    # Redis test
    cache_key = 'home_page_visits'
    visits = cache.get(cache_key, 0)
    cache.set(cache_key, visits + 1, timeout=60)  # Store for 1 minute

    return render(request, 'home.html', {
        'items_link': '/items/',
        'polls_link': '/polls/',
        'visits_count': visits + 1,  # Counter at the context
    })

items/views.py
from django.views.generic import DetailView, CreateView
from django.shortcuts import render
from .models import Item


#FBV
def index_view(request):
    items = Item.objects.all().select_related('inventory').prefetch_related('tags')
    context = {
        'item_list': items
    }
    return render(request,'items/index.html', context)


#CBV
class ItemDetailView(DetailView):
    model = Item


class ItemCreateView(CreateView):
    model = Item
    fields = ('name', 'weight')
    success_url = '/'


# filter
#   Item.objects.filter(name='...')
#   Item.objects.filter(weight=100)
#   Item.objects.filter(weight__lt=100) if weight < 100
#   Item.objects.filter(name__contains='d') if 'd' in name
#   Item.objects.exclude(name__contains='d') if name not contains 'd'
#   Item.objects.filter(inventory__name__startswith='H')

makemigrations/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
               :5
               ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

items/templates/items/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <ul>
    {% for item in item_list %}
        <li>
            <a href="{% url 'items:detail' pk=item.pk %}">{{item.name}} / {{item.weight}}</a>
            ({{item.inventory.name}})

            {% for tag in item.tags.all %}
                {{tag.name}}
            {% endfor %}
        </li>
    {% endfor %}
    </ul>
    <a href="{% url 'items:create' %}">Create item</a>
</body>
</html>

items/templates/items/item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{object.name}}</h1>
<h2>{{object.weight}}</h2>

{{ object|pprint }}

</body>
</html>

items/templates/items/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Item</title>
</head>
<body>
    <h1>Create New Item</h1>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Save</button>
    </form>

    <a href="{% url 'items:index' %}">Back to list</a>
</body>
</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Main project page</title>
</head>
<body>
    <h1>Homework #8</h1>

    <h2>Available applications:</h2>
    <ul>
        <li><a href="{{ items_link }}">Items</a></li>
        <li><a href="{{ polls_link }}">Polls</a></li>
    </ul>
    <p>This page has been opened {{visits_count}} times in the last minute.</p>
</body>
</html>